### ISSUE TITLE
helpers/__init__.py imports 44 submodules that do not exist; package fails to import since c96d1cf

### ISSUE THREAD

**Issue by repowazdogz-droid** [hpn-bristol/agentic-ai-future-factory#1]
On a clean clone of main (c96d1cf) the helpers package cannot be imported, so main.py cannot start:

```
$ git clone https://github.com/hpn-bristol/agentic-ai-future-factory && cd agentic-ai-future-factory
$ python3 -c "import helpers.evaluation"
ImportError: cannot import name 'agent' from 'helpers' (.../helpers/__init__.py)
```

Reproduced with CPython 3.11.15, 3.12.13, 3.13.15 and 3.14.6.

Cause: helpers/__init__.py was an empty file at the initial commit 4396c79, and that revision imports cleanly. The licence-header commit c96d1cf ("ADD - GPL License") added a 51-line `from . import (agent, agent_config, ..., worker_utils)` block naming 44 modules that are not in the tree, so the import fails before any real module loads.

Fix: restore helpers/__init__.py to an empty file (keeping the SPDX header if you want it there). With the import block removed, `import helpers.evaluation` succeeds again on all four interpreters above (main.py additionally needs the packages in requirements.txt, which is expected).

I searched the issues and pull requests (state=all) before filing and found none. I can open a one-line PR for this if that is easier; say so and I will.
